name: "bitsoftly.com"
description: "Bitsoftly helps the world's best software developers make better software.  Check out our team, references, skills and offer."

url: "http://www.bitsoftly.com"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true


analytics :
  provider : google 
  google : 
      tracking_id : 'UA-42470533-1'

